In [4]:
import pandas as pd

In [65]:
pd.options.display.float_format = '{:.2f}'.format

In [ ]:
hdi = pd.read_csv('../../Data/hdi_from2000_cleaned.csv')
happy = pd.read_csv('../../Data/happiness_clean.csv')
# hale = pd.read_csv('../../Data/HALE_clean.csv')
# co2 = pd.read_csv('../../Data/co2_pc_clean.csv')
# footprint = pd.read_csv('../../Data/footprint_clean_2019.csv')
# le = pd.read_csv('../../Data/life_expectancy_clean.csv')
# sdg = pd.read_csv('../../Data/SDG_from2000_clean.csv')
gdp_gni = pd.read_csv('../../Data/GNI_GDP.csv')

In [220]:
hdi[hdi['year'] == 2021]

,iso3,country,hdicode,region,hdi_rank_2022,year,hdi,pop_total
4326,AFG,Afghanistan,Low,SA,182.00,2021,0.47,40.10
4327,ALB,Albania,High,ECA,74.00,2021,0.79,2.85
4328,DZA,Algeria,High,AS,93.00,2021,0.74,44.18
4329,AND,Andorra,Very High,NaN,35.00,2021,0.85,0.08
4330,AGO,Angola,Medium,SSA,150.00,2021,0.59,34.50
...,...,...,...,...,...,...,...,...
4527,ZZG.ECA,Europe and Central Asia,NaN,NaN,NaN,2021,0.80,249.86
4528,ZZH.LAC,Latin America and the Caribbean,NaN,NaN,NaN,2021,0.75,651.10
4529,ZZI.SA,South Asia,NaN,NaN,NaN,2021,0.63,1989.45
4530,ZZJ.SSA,Sub-Saharan Africa,NaN,NaN,NaN,2021,0.55,1118.48
4531,ZZK.WORLD,World,NaN,NaN,NaN,2021,0.73,7874.88

In [140]:
gdp_gni.rename({
    "Entity": "Country", 
    "GNI per capita": "GNI pc", 
    "GDP per capita": "GDP pc", 
    "World region according to OWID": "World region"}, 
    axis=1, 
    inplace=True
    )

In [159]:
happy_gni = happy.merge(gdp_gni, on=['Country', 'Code', 'Year'], how='inner')

In [ ]:
hdi_n = hdi.rename(
    {"country": "Country", 
     "iso3": "Code", 
     "year": "Year", 
     "hdi": "HDI", 
     "region": "Region", 
     "hdicode": "HDICode", 
     "pop_total": "PopTotal"
    })

In [160]:
happy_hdi = hdi_n.merge(happy_gni, on=['Country', 'Code', 'Year'], how='inner')
happy_hdi

,Code,Country,HDICode,Region,hdi_rank_2022,Year,HDI,PopTotal,Happiness Score,GNI pc,GDP pc,Population,World region
0,AFG,Afghanistan,Low,SA,182.00,2011,0.46,29.25,4.26,NaN,2757.05,29347708.00,Asia
1,ALB,Albania,High,ECA,74.00,2011,0.78,2.90,5.13,11936.70,12153.11,2911499.00,Europe
2,DZA,Algeria,High,AS,93.00,2011,0.72,36.54,5.37,16082.68,14641.96,36903374.00,Africa
3,AGO,Angola,Medium,SSA,150.00,2011,0.53,24.26,4.18,11621.38,11037.64,24218358.00,Africa
4,ARG,Argentina,Very High,LAC,48.00,2011,0.84,41.52,6.24,28577.66,29425.76,41730655.00,South America
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,USA,United States,Very High,NaN,20.00,2022,0.93,338.29,6.89,73500.52,72679.26,341534041.00,North America
1457,URY,Uruguay,Very High,LAC,52.00,2022,0.83,3.42,6.49,27494.30,30804.70,3390913.00,South America
1458,UZB,Uzbekistan,High,ECA,106.00,2022,0.73,34.63,6.01,NaN,9607.56,34938953.00,Asia
1459,ZMB,Zambia,Medium,SSA,153.00,2022,0.57,20.02,3.98,NaN,3585.12,20152935.00,Africa
1460,ZWE,Zimbabwe,Medium,SSA,159.00,2022,0.55,16.32,3.20,4899.30,5036.76,16069061.00,Africa

In [161]:
happy_gni_n = happy_hdi[[
       'Country', 
       'Code', 
       'Population',
       'World region',
       'Year', 
       'HDICode', 
       'HDI',
       'GDP pc', 
       'GNI pc', 
       'Happiness Score', 
       ]]

happy_gni_n

,Country,Code,Population,World region,Year,HDICode,HDI,GDP pc,GNI pc,Happiness Score
0,Afghanistan,AFG,29347708.00,Asia,2011,Low,0.46,2757.05,NaN,4.26
1,Albania,ALB,2911499.00,Europe,2011,High,0.78,12153.11,11936.70,5.13
2,Algeria,DZA,36903374.00,Africa,2011,High,0.72,14641.96,16082.68,5.37
3,Angola,AGO,24218358.00,Africa,2011,Medium,0.53,11037.64,11621.38,4.18
4,Argentina,ARG,41730655.00,South America,2011,Very High,0.84,29425.76,28577.66,6.24
...,...,...,...,...,...,...,...,...,...,...
1456,United States,USA,341534041.00,North America,2022,Very High,0.93,72679.26,73500.52,6.89
1457,Uruguay,URY,3390913.00,South America,2022,Very High,0.83,30804.70,27494.30,6.49
1458,Uzbekistan,UZB,34938953.00,Asia,2022,High,0.73,9607.56,NaN,6.01
1459,Zambia,ZMB,20152935.00,Africa,2022,Medium,0.57,3585.12,NaN,3.98
1460,Zimbabwe,ZWE,16069061.00,Africa,2022,Medium,0.55,5036.76,4899.30,3.20

In [180]:
happy_hdi_2021 = happy_hdi[happy_hdi['Year']==2021]
happy_hdi_2021

,Code,Country,HDICode,Region,hdi_rank_2022,Year,HDI,PopTotal,Happiness Score,GNI pc,GDP pc,Population,World region
1212,AFG,Afghanistan,Low,SA,182.00,2021,0.47,40.10,2.40,2157.11,2144.17,40000410.00,Asia
1213,ALB,Albania,High,ECA,74.00,2021,0.79,2.85,5.20,17960.38,18212.87,2849641.00,Europe
1214,DZA,Algeria,High,AS,93.00,2021,0.74,44.18,5.12,14213.31,14496.86,44761099.00,Africa
1215,ARG,Argentina,Very High,LAC,48.00,2021,0.84,45.28,5.97,25772.62,26300.27,45312282.00,South America
1216,ARM,Armenia,High,ECA,76.00,2021,0.77,2.79,5.40,15464.01,15921.70,2870339.00,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335,USA,United States,Very High,NaN,20.00,2021,0.92,337.00,6.98,71767.06,71307.40,340161438.00,North America
1336,URY,Uruguay,Very High,LAC,52.00,2021,0.81,3.43,6.47,26476.34,29431.88,3396693.00,South America
1337,UZB,Uzbekistan,High,ECA,106.00,2021,0.72,34.08,6.06,9290.37,9247.64,34243696.00,Asia
1338,ZMB,Zambia,Medium,SSA,153.00,2021,0.56,19.47,3.76,3198.36,3503.03,19603610.00,Africa
1339,ZWE,Zimbabwe,Medium,SSA,159.00,2021,0.55,15.99,3.00,4751.75,4827.09,15797220.00,Africa

In [ ]:
hpi_2021 = pd.read_clipboard()
hpi_2021.to_csv('../../Data/hpi_2021.csv', index=False)

In [237]:
hpi_2021.columns = hpi_2021.columns.str.strip()
hpi_2021 = hpi_2021.apply(lambda x: x.strip() if isinstance(x, str) else x)

In [ ]:
hpi_2021.columns.tolist()
happy_hdi_2021.columns.tolist()
hpi_2021['Wellbeing'][2]
hpi_2021['Country'][2]

['Code',
 'Country',
 'HDICode',
 'Region',
 'hdi_rank_2022',
 'Year',
 'HDI',
 'PopTotal',
 'Happiness Score',
 'GNI pc',
 'GDP pc',
 'Population',
 'World region']

In [243]:
hpi_2021.to_csv("../../Data/hpi_2021.csv", index=False)

In [246]:
happy_hpi = happy_hdi_2021.merge(hpi_2021, left_on='Country', right_on='Country', how='outer')

In [212]:
# spi = pd.read_csv("../scraper/social_progress_index_2021.csv")
spi.rename(columns={"country": "Country", "score": "SPI Score"}, inplace=True)
spi

     rank               Country  SPI Score
0       1                Norway      90.58
1       2               Denmark      90.38
2       3               Finland      90.06
3       4           Switzerland      89.54
4       5               Iceland      89.44
..    ...                   ...        ...
164   163               Eritrea      35.96
165   164               Somalia      33.85
166   165                  Chad      29.53
167   166  Central African Rep.      27.07
168   167           South Sudan      25.05

[169 rows x 3 columns]

In [223]:
happy_spi_2021 = happy_hpi.merge(spi, on='Country', how='outer')
happy_spi_2021

,Code,Country,HDICode,Region,hdi_rank_2022,Year,HDI,PopTotal,Happiness Score,GNI pc,GDP pc,Population,World region,Rank,Life Expectancy,Wellbeing,Carbon Footprint,HPI score,rank,SPI Score
0,AFG,Afghanistan,Low,SA,182.00,2021.00,0.47,40.10,2.40,2157.11,2144.17,40000410.00,Asia,144th,62 years,2.4/10,1.14 tCO2e,16.20,162.00,37.88
1,ALB,Albania,High,ECA,74.00,2021.00,0.79,2.85,5.20,17960.38,18212.87,2849641.00,Europe,33rd,76.5 years,5.3/10,3.67 tCO2e,46.30,56.00,71.58
2,DZA,Algeria,High,AS,93.00,2021.00,0.74,44.18,5.12,14213.31,14496.86,44761099.00,Africa,29th,76.4 years,5.2/10,3.11 tCO2e,47.40,96.00,63.89
3,NaN,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,147.00,44.26
4,ARG,Argentina,Very High,LAC,48.00,2021.00,0.84,45.28,5.97,25772.62,26300.27,45312282.00,South America,41st,75.4 years,5.9/10,6.39 tCO2e,43.80,40.00,77.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,NaN,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98th,70.6 years,5.1/10,7.37 tCO2e,32.70,114.00,56.58
185,NaN,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36th,73.6 years,5.5/10,3.79 tCO2e,45.50,72.00,68.29
186,NaN,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125th,63.8 years,3.6/10,1.38 tCO2e,26.60,159.00,39.54
187,ZMB,Zambia,Medium,SSA,153.00,2021.00,0.56,19.47,3.76,3198.36,3503.03,19603610.00,Africa,141st,61.2 years,3.1/10,2.23 tCO2e,19.10,137.00,46.96
188,ZWE,Zimbabwe,Medium,SSA,159.00,2021.00,0.55,15.99,3.00,4751.75,4827.09,15797220.00,Africa,139th,59.3 years,3.2/10,0.82 tCO2e,19.70,134.00,48.56

In [255]:
happy_spi_2021.columns
happy_spi_2021_c = happy_spi_2021[
    [
        "Country",
        "Code",
        "Population",
        "World region",
        "Year",
        "GDP pc",
        "GNI pc",
        "HDI",
        "HDICode",
        "Life Expectancy",
        "Wellbeing",
        "Carbon Footprint",
        "HPI score",
        "SPI Score",
        "Happiness Score",
    ]
]

happy_spi_2021_c.to_csv("../../Data/happy_spi_2021.csv", index=False)

In [ ]:
happy_spi_2021.to_csv("../../Data/happy_spi_2021.csv", index=False)

In [256]:
happy_spi_2021 = pd.read_csv("../../Data/happy_spi_2021.csv")
happy_spi_2021

,Country,Code,Population,World region,Year,GDP pc,GNI pc,HDI,HDICode,Life Expectancy,Wellbeing,Carbon Footprint,HPI score,SPI Score,Happiness Score
0,Afghanistan,AFG,40000410.00,Asia,2021.00,2144.17,2157.11,0.47,Low,62 years,2.4/10,1.14 tCO2e,16.20,37.88,2.40
1,Albania,ALB,2849641.00,Europe,2021.00,18212.87,17960.38,0.79,High,76.5 years,5.3/10,3.67 tCO2e,46.30,71.58,5.20
2,Algeria,DZA,44761099.00,Africa,2021.00,14496.86,14213.31,0.74,High,76.4 years,5.2/10,3.11 tCO2e,47.40,63.89,5.12
3,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.26,NaN
4,Argentina,ARG,45312282.00,South America,2021.00,26300.27,25772.62,0.84,Very High,75.4 years,5.9/10,6.39 tCO2e,43.80,77.35,5.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,Venezuela,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.6 years,5.1/10,7.37 tCO2e,32.70,56.58,NaN
185,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.6 years,5.5/10,3.79 tCO2e,45.50,68.29,NaN
186,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63.8 years,3.6/10,1.38 tCO2e,26.60,39.54,NaN
187,Zambia,ZMB,19603610.00,Africa,2021.00,3503.03,3198.36,0.56,Medium,61.2 years,3.1/10,2.23 tCO2e,19.10,46.96,3.76
188,Zimbabwe,ZWE,15797220.00,Africa,2021.00,4827.09,4751.75,0.55,Medium,59.3 years,3.2/10,0.82 tCO2e,19.70,48.56,3.00

In [257]:
happy_spi_2021.columns

Index(['Country', 'Code', 'Population', 'World region', 'Year', 'GDP pc',
       'GNI pc', 'HDI', 'HDICode', 'Life Expectancy', 'Wellbeing',
       'Carbon Footprint', 'HPI score', 'SPI Score', 'Happiness Score'],
      dtype='str')

In [258]:
import altair as alt


hover = alt.selection_point(on='mouseover', nearest=True, fields=['Country'], empty=False)


# 1. Define the variables you want to switch between
column_options = ['GDP pc', 'GNI pc', 'HDI', 'HDICode', 'Life Expectancy', 'Wellbeing', 'Carbon Footprint', 'HPI score', 'SPI Score']

# 2. Create the dropdown menu
dropdown = alt.binding_select(
    options=column_options, 
    name='Choose Wealth Metric: '
)

# 3. Create the parameter that tracks the selection
# 'value' sets the default starting position
select_var = alt.selection_point(
    fields=['column'], 
    bind=dropdown, 
    value=[{'column': column_options[0]}],
    name='Selection',
    toggle=False
)

# 4. Build the chart
chart = alt.Chart(happy_spi_2021).transform_fold(
    column_options,           # "Fold" (melt) these columns
    as_=['column', 'value']   # into two new columns: 'column' (name) and 'value' (number)
).transform_filter(
    "datum.value > 0" # Removes any rows where the metric is missing/zero
).transform_filter(
    select_var              # Filter the data to show only the selected "column"
).mark_point(filled=True, size=100).encode(
    
        x=alt.X('Happiness Score:Q', 
            axis=alt.Axis(
                format='.1f', 
                tickCount=5, 
                labelFontSize=14,  
                titleFontSize=16   
                ),
            scale=alt.Scale(zero=False),
            ), 

        y=alt.Y('value:Q', 
            scale=alt.Scale(zero=False, padding=5),
            title="Wealth Metric",
            axis=alt.Axis(
                tickCount=5,
                labelFontSize=14,  
                titleFontSize=16,
                format='$.0s' , 
                titleAnchor='middle',
                domainColor='#CBD5E1',
                tickColor='#CBD5E1',
                labelColor='#64748B',
                tickSize=5,
                domainWidth=1
    ),
),
    # color='Happiness Score:Q',
    color=alt.Color('Happiness Score:Q', scale=alt.Scale(scheme='redyellowgreen'), legend=None),
    tooltip=[
        alt.Tooltip('Country:N'),
        alt.Tooltip('World region:N'),
        alt.Tooltip('Population:Q'),
        alt.Tooltip('Life Expectancy:Q'),
        alt.Tooltip('GDP pc:Q', format='$.3s', title='GDP pc.'),
        alt.Tooltip('GNI pc:Q', format='$.3s', title='GNI pc.'),
        alt.Tooltip('HDI:Q', title='HDI'),
        alt.Tooltip('HDICode:N', title='HDI Code'),
        alt.Tooltip('Wellbeing:Q', title='Wellbeing'),
        alt.Tooltip('Carbon Footprint:Q', title='Carbon Footprint'),
        alt.Tooltip('HPI score:Q', title='HPI Score'),
        alt.Tooltip('SPI Score:Q', title='SPI Score'),
        alt.Tooltip('Happiness Score:Q', format='.2f'),
    ],
    size=alt.condition(
        hover, 
        alt.value(400),
        alt.Size('Happiness Score:Q', 
        scale=alt.Scale(range=[10, 200]), 
        title='HDI',
        legend=alt.Legend(
            orient='none',          # 1. This is the "detach" command
            legendX=30,             # 2. X position (pixels from left)
            legendY=20,             # 3. Y position (pixels from top)
            fillColor='white',      # 4. Makes the box visible
            padding=10,
            cornerRadius=5,
            # strokeColor='gray',
            direction='vertical',
            labelAlign='center',
            # labelBaseline='top',
            labelOffset=20,
            titleOrient='top',    
            gradientLength=200    # Makes it a bit wider/readable
        )
    )
    )
).add_params(
    select_var
).properties(
    width=800,
    height=500,
    title={
        "text": "Wealth vs Happiness",
        "subtitle": ["GDP pc & GNI pc  "],
        "anchor": "start",
        "offset": 30,
    },
).configure_axis(
    gridColor= "gray",
    gridOpacity=0.1,
    labelColor='gray',
    titleColor='black'
).configure_title(
    fontSize=22,          # Main title size
    subtitleFontSize=18,  # Subtitle size
    subtitleColor='gray'
).add_params(
    hover  
).configure_view(
    strokeOpacity=0.2,
)

# chart.save('chart_spec.json')
chart

alt.Chart(...)

,Rank,Country,Life expectancy,Wellbeing,Carbon footprint,HPI score
0,1st,Vanuatu,70.4 years,7.1/10,2.62 tCO2e,57.90
1,2nd,Sweden,83 years,7.4/10,8.7 tCO2e,55.90
2,3rd,El Salvador,70.7 years,6.4/10,2.03 tCO2e,54.70
3,4th,Costa Rica,77 years,6.4/10,4.37 tCO2e,54.10
4,5th,Nicaragua,73.8 years,6.1/10,2.61 tCO2e,53.60
...,...,...,...,...,...,...
142,143rd,Chad,52.5 years,4.4/10,3.88 tCO2e,18.30
143,144th,Afghanistan,62 years,2.4/10,1.14 tCO2e,16.20
144,145th,Lesotho,53.1 years,3.7/10,3.04 tCO2e,15.60
145,146th,Botswana,61.1 years,3.5/10,10.28 tCO2e,14.70
146,147th,Central African Republic,53.9 years,3.1/10,1.83 tCO2e,13.70