In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://drive.google.com/uc?id=1oE-3rt17bFW7fOzDIjwFSEMPTIV3NvcO")

## Select Columns

In [3]:
df.iloc[:, :4]

      school_id  grade class      student_id
0            57      6     A  wvqgd@cunb.edu
1            57      6     A  j0ihe@cunb.edu
2            57      6     A  wcjgk@cunb.edu
3            57      6     A  mzmqb@cunb.edu
4            57      6     A  s6n0y@cunb.edu
...         ...    ...   ...             ...
1505        946      8     D  jj36e@cunb.edu
1506        946      8     D  ca1dg@cunb.edu
1507        946      8     D  amdrx@cunb.edu
1508        946      8     D  yn5ug@cunb.edu
1509        946      8     A  eohgp@cunb.edu

[1510 rows x 4 columns]

In [4]:
df["grade_language_t1"] # select column by name
df[["sex", "grade_language_t1"]].head() # select columns by name

   sex  grade_language_t1
0    1           2.369783
1    1           7.206984
2    2           8.057449
3    1           7.388008
4    1           6.773626

###  filter()

In [5]:
# alternative with extra functionality
df.filter(["sex", "grade_language_t1"])
df.filter(items=["sex", "grade"]) # select columns

# regex filtering
df.filter(regex="^grade", axis=1) # select columns with "grade" at the start of their name
df.filter(regex="t2$", axis=1) # select columns with "t2" at the end

# fuzzy filtering
df.filter(regex="^grade") # all columns that start with 'grade'
df.filter(like="math", axis=1) # select columns with "math" in their name

      grade_math_t1  grade_math_t2
0          2.046285       1.175309
1          7.859077       7.548812
2          7.118976       6.181019
3          6.973737       7.593102
4          6.574877       7.611065
...             ...            ...
1505       4.938375       6.162418
1506       7.661931       8.179364
1507       9.248758       8.773601
1508       5.689228       6.382995
1509       9.768719       9.515601

[1510 rows x 2 columns]

In [6]:
df.columns # see all column names

# reorder columns
df = df[['school_id', 'grade', 'class', 'student_id', 'treatment', 'sex', 'date_of_birth', 'nationality',
       'grade_math_t1', 'grade_language_t1', 'grade_science_t1',
       'grade_math_t2', 'grade_language_t2', 'grade_science_t2',
       ]]

df

,school_id,grade,class,student_id,treatment,sex,date_of_birth,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2
0,57,6,A,wvqgd@cunb.edu,1,1,1997-07-27,1,2.046285,2.369783,2.711344,1.175309,1.498807,1.840368
1,57,6,A,j0ihe@cunb.edu,1,1,1997-06-24,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190
2,57,6,A,wcjgk@cunb.edu,1,2,1997-04-23,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253
3,57,6,A,mzmqb@cunb.edu,1,1,1997-02-24,1,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812
4,57,6,A,s6n0y@cunb.edu,1,1,1996-09-05,1,6.574877,6.773626,7.844316,7.611065,7.809814,8.880504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,946,8,D,jj36e@cunb.edu,0,1,1995-07-04,1,4.938375,5.306647,4.985917,6.162418,6.530690,6.209960
1506,946,8,D,ca1dg@cunb.edu,0,1,1995-08-23,1,7.661931,8.360153,7.937165,8.179364,8.877586,8.454598
1507,946,8,D,amdrx@cunb.edu,0,1,1994-12-15,1,9.248758,8.534791,8.056641,8.773601,8.059634,7.581484
1508,946,8,D,yn5ug@cunb.edu,0,1,1994-09-18,2,5.689228,5.071503,5.338547,6.382995,5.765270,6.032315
1509,946,8,A,eohgp@cunb.edu,0,1,1994-12-19,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953

## Index Rows
accessing specific positions (rows/cells)

In [7]:
# create a new dataframe with a string index
df_name = df[["student_id", "grade_language_t1", "school_id"]].set_index("student_id") # set index to a column
df_name.head()

# loc[] selects by name
df_name.loc["j0ihe@cunb.edu"][['school_id', 'grade_language_t1']] # select row by name

school_id            57.000000
grade_language_t1     7.206984
Name: j0ihe@cunb.edu, dtype: float64

In [8]:
# iloc[] selects by index
df.iloc[1509][:2]  # happens to be the same as name

school_id    946
grade          8
Name: 1509, dtype: object

In [9]:
# indexing by row/col name
df_name.at["j0ihe@cunb.edu", "school_id"]  = 9999  # set value of single cell
df_name.at["j0ihe@cunb.edu", "school_id"]  # single cell

df_name["j0ihe@cunb.edu":].head()

                grade_language_t1  school_id
student_id
j0ihe@cunb.edu           7.206984       9999
wcjgk@cunb.edu           8.057449         57
mzmqb@cunb.edu           7.388008         57
s6n0y@cunb.edu           6.773626         57
valwu@cunb.edu           8.237650         57

In [10]:
# indexing by row/col position
df.iat[1502, 3] = "eohgp-ws@cunb.edu" # update value of single cell
df.iat[1502, 3] # row 1509, col 3 (email)

df[1500:1505]

,school_id,grade,class,student_id,treatment,sex,date_of_birth,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2
1500,946,8,D,qluoj@cunb.edu,0,1,1994-09-10,1,8.028151,7.721704,7.121938,8.315637,8.009190,7.409424
1501,946,8,D,vykat@cunb.edu,0,1,1994-12-22,1,4.184713,4.957843,5.457136,4.862387,5.635517,6.134810
1502,946,8,D,eohgp-ws@cunb.edu,0,1,1994-10-16,1,7.927814,7.530684,8.848721,6.007431,5.610300,6.928337
1503,946,8,D,2hk9v@cunb.edu,0,1,1995-02-05,1,6.553834,6.540934,6.760266,4.893724,4.880824,5.100157
1504,946,8,D,gt35i@cunb.edu,0,1,1994-09-11,1,6.562941,6.272435,6.632548,6.189953,5.899447,6.259560

In [11]:
df.loc[200:204]  # select rows by name sliced -> from : to
df[200:204]  # select rows by index sliced -> from : to

# names in the index
df_id = df.set_index("student_id", drop=True)
df_id.loc[['j0ihe@cunb.edu', 'mzmqb@cunb.edu']]
# df_id.iloc[['j0ihe@cunb.edu', 'mzmqb@cunb.edu']] # does not work because iloc only accepts integer positions

df_id[1:4]
df_id.iloc[1:4]

,school_id,grade,class,treatment,sex,date_of_birth,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2
student_id,,,,,,,,,,,,,
j0ihe@cunb.edu,57,6,A,1,1,1997-06-24,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190
wcjgk@cunb.edu,57,6,A,1,2,1997-04-23,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253
mzmqb@cunb.edu,57,6,A,1,1,1997-02-24,1,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812

### Slicing
Slicing means getting a range of rows using position

In [12]:
df[:10] # row from index 0 to 9, all cols
df[::30] # every 30th row, all cols
df[:10:2][["school_id"]] # every 2nd row from index 0 to 9, only school_id column

   school_id
0         57
2         57
4         57
6         57
8         57

In [ ]:
# slicing rows, columns


# slicing rows and columns with loc
# loc works on labels we thus use df_id which has a string index
df_id.loc[:'mzmqb@cunb.edu', ["sex", "school_id"]]  # slice of rows and selection of columns
df_id.loc[:, "sex": "grade_language_t1"]  # get all row from col 'b' & 'c'
df_id.loc['mzmqb@cunb.edu':'valwu@cunb.edu', "sex": "grade_language_t1"]  # get rows from : to, of columns from:to
df_id.loc['mzmqb@cunb.edu':'valwu@cunb.edu', :]  # get rows - from : to & all columns

,school_id,grade,class,treatment,sex,date_of_birth,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2
student_id,,,,,,,,,,,,,
mzmqb@cunb.edu,57,6,A,1,1,1997-02-24,1,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812
s6n0y@cunb.edu,57,6,A,1,1,1996-09-05,1,6.574877,6.773626,7.844316,7.611065,7.809814,8.880504
valwu@cunb.edu,57,6,A,1,1,1997-06-18,1,7.041647,8.237650,7.133128,6.269658,7.465661,6.361139

In [ ]:
# slicing rows and columns with iloc = index location
df.iloc[0:3]  # first 3 rows by index
df.iloc[:, -1]  # select last column by index
df.iloc[0:3, :]  #  Slicing Rows and Columns by position
df.iloc[:, 0:3]  # slice columns by index position.
df.iloc[0:2, 1:3]  # slice row and columns by index position.
df.iloc[:2, :2]  # row index 0 to index 1 (exclusive 2), column zero to one

df.iloc[0:20:4, 0:4]  # row index 0 to 20 (step 4), column index 0 to 4
df.iloc[10::-1] # reverse the order of rows from index 10 to the beginning

## sample()

In [14]:
df.sample(3) # random sample of 10 rows
df.sample(frac=0.01) # random sample of 10% of rows

,school_id,grade,class,student_id,treatment,sex,date_of_birth,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2
83,57,7,C,cnbcv@cunb.edu,0,1,1996-01-22,2,4.419185,5.455389,5.255909,4.359435,5.395639,5.196159
1410,946,6,D,cpnpz@cunb.edu,1,1,1997-01-29,1,9.240482,7.565840,8.662684,9.437043,7.762400,8.859245
608,426,6,B,ppmsj@cunb.edu,1,1,1997-01-09,1,7.333949,6.585416,8.335276,7.153728,6.405195,8.155054
1415,946,7,A,vahty@cunb.edu,1,1,1996-01-25,2,5.921797,5.241740,5.906436,7.071328,6.391271,7.055967
1053,499,8,A,e9whz@cunb.edu,1,1,1995-01-06,1,8.268938,7.926082,8.258870,9.584604,9.241748,9.574536
687,426,7,D,d9c0m@cunb.edu,1,2,1996-04-10,1,4.347667,3.406501,2.582010,3.717383,2.776217,1.951726
60,57,7,A,7yobi@cunb.edu,1,1,1996-02-18,1,5.284817,5.648459,5.065093,5.782994,6.146636,5.563270
987,499,7,D,5kxok@cunb.edu,1,1,1995-10-01,1,4.989191,5.888713,6.061920,5.393601,6.293123,6.466330
1274,881,7,A,hjbwz@cunb.edu,0,1,1996-04-19,2,8.872582,8.072096,7.409320,9.281159,8.480672,7.817896
794,458,7,A,cm7tj@cunb.edu,1,2,1996-08-28,1,9.726741,9.277647,8.730910,9.325816,8.876722,8.329985
921,499,6,D,xio5c@cunb.edu,0,1,1997-06-04,1,8.987629,7.233961,7.411075,10.000000,10.000000,10.000000
474,262,6,C,mqfka@cunb.edu,1,1,1997-01-17,1,5.377370,5.729710,4.871069,6.856302,7.208642,6.350002
132,57,8,B,g4wdg@cunb.edu,0,1,1994-11-15,1,7.060272,6.452201,6.479474,5.740346,5.132275,5.159548
1427,946,7,B,zuujs@cunb.edu,1,2,1996-08-08,1,5.801412,6.330598,6.151530,5.992671,6.521857,6.342788
315,141,6,B,uj964@cunb.edu,0,1,1997-02-05,1,2.784872,2.898923,2.362678,4.530953,4.645005,4.108760